export type PoolSportKey =
  | "nfl"
  | "ncaaf"
  | "ncaab"
  | "nba"
  | "mlb"
  | "nhl"
  | "golf"
  | "mma"
  | "nascar"
  | "soccer"
  | "multi_sport";

export type PoolTemplateKey =
  | "pickem"
  | "ats_pickem"
  | "confidence"
  | "ats_confidence"
  | "survivor"
  | "squares"
  | "bracket"
  | "prop"
  | "streak"
  | "upset_underdog"
  | "stat_performance"
  | "last_man_standing"
  | "bundle_pool";

export type ScheduleType = "daily" | "weekly" | "tournament" | "season_long";

export interface PoolTypeRuleVariant {
  key: string;
  label: string;
}

export interface PoolTypeDefinition {
  key: string;
  name: string;
  sport: PoolSportKey;
  template: PoolTemplateKey;
  league_or_tournament: string;
  schedule_type: ScheduleType[];
  scoring_mode: string[];
  pick_mode: string[];
  elimination_mode: string[];
  leaderboard_mode: string[];
  entry_mode: string[];
  commissioner_options: string[];
  payout_bucket_support: boolean;
  multi_pool_bundle_support: boolean;
  rule_variants: PoolTypeRuleVariant[];
  aliases?: string[];
  description: string;
}

const BASE_COMMISSIONER_OPTIONS = [
  "visibility_private_invite_public",
  "sport_league_tournament_selection",
  "game_selection_mode",
  "selected_games_or_all_games",
  "number_of_picks",
  "entries_per_account",
  "entry_naming_behavior",
  "hidden_picks",
  "deadlines",
  "late_entry_rules",
  "missed_pick_behavior",
  "tiebreakers",
  "scoring_multipliers",
  "bonus_rules",
  "drop_worst_period",
  "best_x_count",
  "round_weighting",
  "progressive_payouts",
  "custom_payout_buckets",
  "leaderboard_type",
  "custom_rule_text",
] as const;

const NFL_PICKEM_OPTIONS = [
  "all_games_or_selected_games",
  "weekly_or_season",
  "points_per_win",
  "lock_pick",
  "double_points",
  "triple_points",
  "confidence_ranking",
  "upset_bonus",
  "blowout_bonus",
  "exact_margin_bonus",
  "game_of_the_week",
  "rivalry_game_bonus",
  "drop_worst_week",
  "best_x_weeks_count",
  "playoff_multiplier",
  "secret_picks",
  "joker_pick",
  "redemption_week",
  "weekly_winners",
  "season_leaderboard",
  "hidden_picks_until_kickoff",
  "entry_deadline",
  "missed_pick_defaults",
  "auto_pick_favorite_random_none",
  "late_join_toggle",
  "tie_handling",
] as const;

const NFL_SURVIVOR_OPTIONS = [
  "one_life",
  "two_lives",
  "three_strikes",
  "buy_back_weeks",
  "late_entry",
  "entry_cutoff_week",
  "multiple_entries_per_account",
  "same_name_numbering_or_custom_names",
  "repick_if_canceled",
  "repick_if_tie",
  "hide_picks_until_kickoff",
  "auto_pick_if_user_forgets",
] as const;

const SQUARES_OPTIONS = [
  "single_game_or_weekly_or_season_board",
  "commissioner_selected_game",
  "fan_specific_games",
  "multiple_boards",
  "quarter_halftime_final_or_custom_payouts",
  "random_or_manual_number_draw",
  "multiple_squares_per_user",
  "entry_price_per_square",
  "weekly_redraw_toggle",
] as const;

const BUNDLE_OPTIONS = [
  "bundle_master_record",
  "linked_child_pool_records",
  "payout_allocation_by_category",
  "shared_entry_list",
  "per_pool_standings",
  "overall_bundle_standings",
  "survival_independence_per_child_pool",
  "shared_or_independent_participants",
] as const;

function slug(input: string): string {
  return input.trim().toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "");
}

function def(
  input: Omit<PoolTypeDefinition, "commissioner_options" | "rule_variants"> & {
    commissioner_options?: string[];
    rule_variants?: PoolTypeRuleVariant[];
  },
): PoolTypeDefinition {
  return {
    ...input,
    commissioner_options: Array.from(new Set([...(input.commissioner_options || []), ...BASE_COMMISSIONER_OPTIONS])),
    rule_variants: input.rule_variants && input.rule_variants.length > 0
      ? input.rule_variants
      : [{ key: "standard", label: "Standard" }],
  };
}

export const SUPPORTED_SPORTS: PoolSportKey[] = [
  "nfl",
  "ncaaf",
  "ncaab",
  "nba",
  "mlb",
  "nhl",
  "golf",
  "mma",
  "nascar",
  "soccer",
  "multi_sport",
];

export const CORE_POOL_TEMPLATES: PoolTemplateKey[] = [
  "pickem",
  "ats_pickem",
  "confidence",
  "ats_confidence",
  "survivor",
  "squares",
  "bracket",
  "prop",
  "streak",
  "upset_underdog",
  "stat_performance",
  "last_man_standing",
  "bundle_pool",
];

export const POOL_TYPE_CATALOG: PoolTypeDefinition[] = [
  // NFL
  def({
    key: "nfl_pickem_pool",
    name: "NFL Pick'em Pool",
    sport: "nfl",
    template: "pickem",
    league_or_tournament: "NFL",
    schedule_type: ["weekly", "season_long"],
    scoring_mode: ["straight_winner", "confidence", "bonuses"],
    pick_mode: ["single_game_pick", "multi_game_pick"],
    elimination_mode: ["none"],
    leaderboard_mode: ["weekly", "season"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    commissioner_options: [...NFL_PICKEM_OPTIONS],
    rule_variants: [
      { key: "classic_pickem", label: "Classic Pick'em" },
      { key: "confidence_pickem", label: "Confidence Pick'em" },
      { key: "chaos_pickem", label: "Chaos Pick'em" },
    ],
    aliases: ["pickem", "pick-em", "pick_em"],
    description: "NFL straight winner pick'em with confidence and bonus variants.",
  }),
  def({
    key: "nfl_ats_pickem_pool",
    name: "NFL ATS Pick'em",
    sport: "nfl",
    template: "ats_pickem",
    league_or_tournament: "NFL",
    schedule_type: ["weekly", "season_long"],
    scoring_mode: ["ats_win_loss_push", "confidence_optional"],
    pick_mode: ["spread_pick"],
    elimination_mode: ["none"],
    leaderboard_mode: ["weekly", "season"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    rule_variants: [
      { key: "classic_ats", label: "Classic ATS" },
      { key: "confidence_ats", label: "Confidence ATS" },
      { key: "high_roller_ats", label: "High Roller ATS" },
    ],
    aliases: ["ats"],
    description: "NFL ATS pick'em with classic and high-roller variants.",
  }),
  def({
    key: "nfl_confidence_pool",
    name: "NFL Confidence Pool",
    sport: "nfl",
    template: "confidence",
    league_or_tournament: "NFL",
    schedule_type: ["weekly", "season_long", "tournament"],
    scoring_mode: ["confidence_rank_points", "bonus_lock_joker_perfect"],
    pick_mode: ["ranked_confidence_picks"],
    elimination_mode: ["none"],
    leaderboard_mode: ["weekly", "season", "playoff"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    rule_variants: [
      { key: "classic_confidence", label: "Classic Confidence" },
      { key: "high_stakes_confidence", label: "High Stakes Confidence" },
      { key: "playoff_confidence", label: "Playoff Confidence" },
      { key: "lock_confidence", label: "Lock Confidence" },
      { key: "joker_week", label: "Joker Week" },
      { key: "perfect_week_bonus", label: "Perfect Week Bonus" },
    ],
    aliases: ["confidence"],
    description: "NFL confidence ranking pool with lock/joker/perfect-week twists.",
  }),
  def({
    key: "nfl_ats_confidence_pool",
    name: "NFL ATS Confidence Pool",
    sport: "nfl",
    template: "ats_confidence",
    league_or_tournament: "NFL",
    schedule_type: ["weekly", "season_long", "tournament"],
    scoring_mode: ["ats_confidence_rank_points", "bonus_modes"],
    pick_mode: ["ranked_spread_picks"],
    elimination_mode: ["none"],
    leaderboard_mode: ["weekly", "season", "playoff"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    rule_variants: [
      { key: "classic_ats_confidence", label: "Classic ATS Confidence" },
      { key: "high_stakes_ats_confidence", label: "High Stakes ATS Confidence" },
      { key: "playoff_ats_confidence", label: "Playoff ATS Confidence" },
    ],
    description: "Confidence-style pool scored on spread outcomes.",
  }),
  def({
    key: "nfl_survivor_variants_pool",
    name: "NFL Survivor Variants",
    sport: "nfl",
    template: "survivor",
    league_or_tournament: "NFL",
    schedule_type: ["weekly", "season_long"],
    scoring_mode: ["survival", "optional_bonus"],
    pick_mode: ["single_pick", "variant_specific"],
    elimination_mode: ["one_life", "multi_life", "strikes", "buy_back"],
    leaderboard_mode: ["survival_remaining", "last_alive", "season"],
    entry_mode: ["single_entry", "multi_entry", "custom_named_entries"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    commissioner_options: [...NFL_SURVIVOR_OPTIONS],
    rule_variants: [
      { key: "classic_survivor", label: "Classic Survivor" },
      { key: "ats_survivor", label: "ATS Survivor" },
      { key: "pick_the_loser_survivor", label: "Pick the Loser Survivor" },
      { key: "fantasy_team_survivor", label: "Fantasy Team Survivor" },
      { key: "player_survivor", label: "Player Survivor" },
      { key: "underdog_survivor", label: "Underdog Survivor" },
      { key: "margin_survivor", label: "Margin Survivor" },
      { key: "defense_survivor", label: "Defense Survivor" },
      { key: "prop_survivor", label: "Prop Survivor" },
      { key: "touchdown_scorer_survivor", label: "Touchdown Scorer Survivor" },
    ],
    aliases: ["survivor"],
    description: "Full NFL survivor family including 10 approved variants.",
  }),
  def({
    key: "nfl_squares_pool",
    name: "NFL Squares",
    sport: "nfl",
    template: "squares",
    league_or_tournament: "NFL",
    schedule_type: ["daily", "weekly", "season_long"],
    scoring_mode: ["board_square_payouts", "quarter_halftime_final_custom"],
    pick_mode: ["square_selection", "board_assignment"],
    elimination_mode: ["none"],
    leaderboard_mode: ["board_results", "weekly", "season"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    commissioner_options: [...SQUARES_OPTIONS],
    rule_variants: [
      { key: "single_game_squares", label: "Single Game Squares" },
      { key: "weekly_game_squares", label: "Weekly Game Squares" },
      { key: "season_squares_pool", label: "Season Squares Pool" },
    ],
    aliases: ["squares"],
    description: "Single game, weekly, and season-long NFL squares boards.",
  }),
  def({
    key: "nfl_playoff_pool",
    name: "NFL Playoff Pool",
    sport: "nfl",
    template: "pickem",
    league_or_tournament: "NFL Playoffs",
    schedule_type: ["tournament"],
    scoring_mode: ["round_weighted_points", "perfect_round_bonus", "ats_optional"],
    pick_mode: ["weekly_playoff_picks"],
    elimination_mode: ["none"],
    leaderboard_mode: ["round", "playoff"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    commissioner_options: ["wildcard_divisional_conference_superbowl_rounds", "super_bowl_tiebreaker", "lock_before_kickoff"],
    rule_variants: [{ key: "weekly_playoff_pickem", label: "Weekly Playoff Pick'em" }],
    description: "Weekly playoff picks across all NFL playoff rounds.",
  }),
  def({
    key: "nfl_prop_pool",
    name: "NFL Prop Pools",
    sport: "nfl",
    template: "prop",
    league_or_tournament: "NFL",
    schedule_type: ["daily", "weekly", "tournament"],
    scoring_mode: ["points_per_prop", "tiebreaker_question"],
    pick_mode: ["prop_selection"],
    elimination_mode: ["none"],
    leaderboard_mode: ["weekly", "event", "season"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    commissioner_options: ["number_of_props", "custom_props", "lock_time", "partial_submissions"],
    rule_variants: [
      { key: "weekly_prop_pool", label: "Weekly Prop Pool" },
      { key: "single_game_prop_pool", label: "Single Game Prop Pool" },
      { key: "super_bowl_prop_pool", label: "Super Bowl Prop Pool" },
    ],
    aliases: ["props"],
    description: "Weekly, game-level, and Super Bowl prop pool variants.",
  }),
  def({
    key: "nfl_margin_of_victory_pool",
    name: "NFL Margin of Victory Pool",
    sport: "nfl",
    template: "stat_performance",
    league_or_tournament: "NFL",
    schedule_type: ["daily", "weekly", "season_long"],
    scoring_mode: ["exact", "closest", "range_bucket"],
    pick_mode: ["margin_prediction"],
    elimination_mode: ["none"],
    leaderboard_mode: ["weekly", "season"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    rule_variants: [
      { key: "exact_margin", label: "Exact Margin" },
      { key: "closest_margin", label: "Closest Margin" },
      { key: "range_bucket", label: "Range Bucket Mode" },
    ],
    description: "Predict margin-of-victory in exact, closest, or range modes.",
  }),
  def({
    key: "nfl_underdog_pool",
    name: "NFL Underdog Pool",
    sport: "nfl",
    template: "upset_underdog",
    league_or_tournament: "NFL",
    schedule_type: ["weekly", "season_long"],
    scoring_mode: ["simple", "spread_value"],
    pick_mode: ["one_or_multiple_underdogs"],
    elimination_mode: ["none"],
    leaderboard_mode: ["weekly", "season"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    rule_variants: [
      { key: "single_dog_weekly", label: "Single Underdog Weekly" },
      { key: "multi_dog_weekly", label: "Multiple Underdogs Weekly" },
    ],
    aliases: ["underdog"],
    description: "Underdog-first pool with simple or spread-value scoring.",
  }),
  def({
    key: "nfl_upset_pool",
    name: "NFL Upset Pool",
    sport: "nfl",
    template: "upset_underdog",
    league_or_tournament: "NFL",
    schedule_type: ["weekly", "season_long"],
    scoring_mode: ["spread_value", "fixed_points_optional"],
    pick_mode: ["minimum_one_upset", "multi_upset_optional"],
    elimination_mode: ["none"],
    leaderboard_mode: ["weekly_optional", "season"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    aliases: ["upset"],
    rule_variants: [{ key: "season_upset", label: "Season Upset Pool" }],
    description: "Cumulative upset scoring with optional fixed-point mode.",
  }),
  def({
    key: "nfl_streak_pool",
    name: "NFL Streak Pool",
    sport: "nfl",
    template: "streak",
    league_or_tournament: "NFL",
    schedule_type: ["weekly", "season_long"],
    scoring_mode: ["current_streak", "max_streak"],
    pick_mode: ["one_to_all_games", "ats_or_straight"],
    elimination_mode: ["streak_reset_on_loss"],
    leaderboard_mode: ["highest_streak"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    commissioner_options: ["minimum_picks_per_week", "allow_skipping_weeks", "hidden_picks_until_kickoff"],
    aliases: ["streak"],
    rule_variants: [{ key: "max_streak_season", label: "Highest Streak Wins" }],
    description: "Loss resets streak; highest season streak wins.",
  }),
  def({
    key: "nfl_supercontest_style_pool",
    name: "NFL SuperContest Style Pool",
    sport: "nfl",
    template: "ats_pickem",
    league_or_tournament: "NFL",
    schedule_type: ["weekly", "season_long"],
    scoring_mode: ["win_1_loss_0_push_0_5"],
    pick_mode: ["fixed_ats_pick_count"],
    elimination_mode: ["none"],
    leaderboard_mode: ["weekly", "season"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    commissioner_options: ["weekly_pick_count_3_5_7_custom", "weekly_prizes", "hidden_picks", "late_entry_toggle"],
    rule_variants: [{ key: "supercontest_classic", label: "SuperContest Classic" }],
    description: "Fixed ATS card each week with push support.",
  }),
  def({
    key: "nfl_total_points_pool",
    name: "NFL Total Points Pool",
    sport: "nfl",
    template: "stat_performance",
    league_or_tournament: "NFL",
    schedule_type: ["weekly", "season_long"],
    scoring_mode: ["closest_total_points_prediction"],
    pick_mode: ["total_points_prediction"],
    elimination_mode: ["none"],
    leaderboard_mode: ["weekly", "season"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    rule_variants: [{ key: "total_points_classic", label: "Total Points Classic" }],
    description: "Predict combined points outcomes by game/week.",
  }),
  def({
    key: "nfl_first_touchdown_pool",
    name: "NFL First Touchdown Pool",
    sport: "nfl",
    template: "prop",
    league_or_tournament: "NFL",
    schedule_type: ["daily", "weekly"],
    scoring_mode: ["first_td_correct_pick"],
    pick_mode: ["first_td_scorer_pick"],
    elimination_mode: ["none"],
    leaderboard_mode: ["weekly", "season"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    rule_variants: [{ key: "first_td_classic", label: "First Touchdown Classic" }],
    description: "Pick the first touchdown scorer in selected games.",
  }),

  // College Football
  def({
    key: "cfb_top_25_pickem_pool",
    name: "College Football Top-25 Pick'em",
    sport: "ncaaf",
    template: "pickem",
    league_or_tournament: "Top-25",
    schedule_type: ["weekly", "season_long"],
    scoring_mode: ["straight_winner", "ats_optional"],
    pick_mode: ["featured_game_cards"],
    elimination_mode: ["none"],
    leaderboard_mode: ["weekly", "season"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    rule_variants: [{ key: "top_25_classic", label: "Top-25 Classic" }],
    description: "Featured ranked-game pick'em for college football.",
  }),
  def({
    key: "cfb_ats_pickem_pool",
    name: "College Football ATS Pick'em",
    sport: "ncaaf",
    template: "ats_pickem",
    league_or_tournament: "NCAAF",
    schedule_type: ["weekly", "season_long"],
    scoring_mode: ["ats_win_loss_push"],
    pick_mode: ["spread_pick"],
    elimination_mode: ["none"],
    leaderboard_mode: ["weekly", "season"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    rule_variants: [{ key: "cfb_ats_classic", label: "CFB ATS Classic" }],
    description: "ATS pool for college football slates.",
  }),
  def({
    key: "cfb_confidence_pool",
    name: "College Football Confidence Pool",
    sport: "ncaaf",
    template: "confidence",
    league_or_tournament: "NCAAF",
    schedule_type: ["weekly", "season_long"],
    scoring_mode: ["confidence_rank_points"],
    pick_mode: ["ranked_confidence_picks"],
    elimination_mode: ["none"],
    leaderboard_mode: ["weekly", "season"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    rule_variants: [{ key: "cfb_confidence_classic", label: "CFB Confidence" }],
    description: "College football confidence pick pool.",
  }),
  def({
    key: "cfb_upset_pool",
    name: "College Football Upset Pool",
    sport: "ncaaf",
    template: "upset_underdog",
    league_or_tournament: "NCAAF",
    schedule_type: ["weekly", "season_long"],
    scoring_mode: ["underdog_value"],
    pick_mode: ["upset_pick"],
    elimination_mode: ["none"],
    leaderboard_mode: ["weekly", "season"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    rule_variants: [{ key: "cfb_upset_classic", label: "CFB Upset" }],
    description: "Underdog/upset scoring for CFB.",
  }),
  def({
    key: "cfb_survivor_pool",
    name: "College Football Survivor Pool",
    sport: "ncaaf",
    template: "survivor",
    league_or_tournament: "NCAAF",
    schedule_type: ["weekly", "season_long"],
    scoring_mode: ["survival"],
    pick_mode: ["single_pick"],
    elimination_mode: ["one_life", "multi_life", "buy_back"],
    leaderboard_mode: ["survival_remaining", "last_alive"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    rule_variants: [{ key: "cfb_survivor_classic", label: "CFB Survivor" }],
    description: "Survivor-style elimination pool for college football.",
  }),
  def({
    key: "cfb_chaos_underdog_pool",
    name: "College Football Chaos Underdog Pool",
    sport: "ncaaf",
    template: "upset_underdog",
    league_or_tournament: "NCAAF",
    schedule_type: ["weekly", "season_long"],
    scoring_mode: ["odds_weighted_upset"],
    pick_mode: ["underdog_only"],
    elimination_mode: ["none"],
    leaderboard_mode: ["weekly", "season"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    rule_variants: [{ key: "chaos_underdog", label: "Chaos Underdog" }],
    description: "High-variance underdog pool for CFB chaos weeks.",
  }),
  def({
    key: "cfb_pick_6_contest",
    name: "College Football Pick-6 Contest",
    sport: "ncaaf",
    template: "pickem",
    league_or_tournament: "NCAAF",
    schedule_type: ["weekly"],
    scoring_mode: ["win_loss_push"],
    pick_mode: ["featured_5_6_7_custom"],
    elimination_mode: ["none"],
    leaderboard_mode: ["weekly", "season"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    commissioner_options: ["featured_game_count_5_6_7_custom", "ats_or_straight"],
    rule_variants: [{ key: "pick6_classic", label: "Pick-6 Classic" }],
    description: "Featured game pick card with configurable slate size.",
  }),
  def({
    key: "cfb_bowl_mania_pool",
    name: "College Football Bowl Mania Pool",
    sport: "ncaaf",
    template: "confidence",
    league_or_tournament: "Bowl Season",
    schedule_type: ["tournament"],
    scoring_mode: ["straight_or_confidence"],
    pick_mode: ["bowl_card"],
    elimination_mode: ["none"],
    leaderboard_mode: ["bowl_event"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    commissioner_options: ["hidden_until_bowl_start", "championship_tiebreaker"],
    rule_variants: [
      { key: "bowl_mania_straight", label: "Bowl Mania Straight Picks" },
      { key: "bowl_mania_confidence", label: "Bowl Mania Confidence" },
    ],
    description: "Bowl-season straight and confidence modes.",
  }),
  def({
    key: "cfb_bowl_game_pickem_pool",
    name: "College Football Bowl Game Pick'em",
    sport: "ncaaf",
    template: "pickem",
    league_or_tournament: "Bowl Games",
    schedule_type: ["tournament"],
    scoring_mode: ["straight_winner"],
    pick_mode: ["bowl_game_pickem"],
    elimination_mode: ["none"],
    leaderboard_mode: ["bowl_event"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    rule_variants: [{ key: "bowl_pickem", label: "Bowl Game Pick'em" }],
    description: "Straight-up pick'em for all bowl games.",
  }),

  // College Basketball
  def({
    key: "cbb_march_madness_bracket_pool",
    name: "March Madness Bracket Pool",
    sport: "ncaab",
    template: "bracket",
    league_or_tournament: "March Madness",
    schedule_type: ["tournament"],
    scoring_mode: ["round_weighted", "bonus_cinderella_perfect_loyalty"],
    pick_mode: ["full_bracket", "re_entry_brackets"],
    elimination_mode: ["none"],
    leaderboard_mode: ["tournament", "round"],
    entry_mode: ["single_entry", "multi_entry", "custom_named_entries"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    aliases: ["bracket"],
    rule_variants: [
      { key: "march_madness_classic", label: "March Madness Bracket" },
      { key: "confidence_bracket", label: "Confidence Bracket" },
      { key: "upset_madness", label: "Upset Madness" },
      { key: "final_four_pool", label: "Final Four Pool" },
      { key: "sweet_16_pool", label: "Sweet 16 Pool" },
      { key: "survivor_madness", label: "Survivor Madness" },
      { key: "perfect_bracket_challenge", label: "Perfect Bracket Challenge Style" },
    ],
    description: "Comprehensive March Madness bracket ecosystem with bonuses.",
  }),
  def({
    key: "cbb_single_game_squares_pool",
    name: "College Basketball Single Game Squares",
    sport: "ncaab",
    template: "squares",
    league_or_tournament: "NCAAB",
    schedule_type: ["daily"],
    scoring_mode: ["board_square_payouts"],
    pick_mode: ["square_selection"],
    elimination_mode: ["none"],
    leaderboard_mode: ["game_board"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    commissioner_options: [...SQUARES_OPTIONS],
    rule_variants: [{ key: "single_game_squares", label: "Single Game Squares" }],
    description: "Single game squares board for college basketball.",
  }),
  def({
    key: "cbb_tournament_squares_pool",
    name: "College Basketball Tournament Squares",
    sport: "ncaab",
    template: "squares",
    league_or_tournament: "NCAAB Tournament",
    schedule_type: ["tournament"],
    scoring_mode: ["progressive_round_weights", "custom_round_weights"],
    pick_mode: ["single_board_across_tournament"],
    elimination_mode: ["none"],
    leaderboard_mode: ["tournament_board"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    rule_variants: [{ key: "tournament_squares", label: "Tournament Squares" }],
    description: "One board across all tournament games with weighted payouts.",
  }),
  def({
    key: "cbb_calcutta_pool",
    name: "College Basketball Calcutta Pool",
    sport: "ncaab",
    template: "stat_performance",
    league_or_tournament: "NCAAB Tournament",
    schedule_type: ["tournament"],
    scoring_mode: ["auction_team_ownership", "round_payout_structure"],
    pick_mode: ["auction_ownership_records"],
    elimination_mode: ["none"],
    leaderboard_mode: ["ownership_roi", "payout_rank"],
    entry_mode: ["single_entry", "co_ownership_optional"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    commissioner_options: ["co_ownership_optional", "trading_hooks_optional", "buy_back_hooks_optional"],
    rule_variants: [{ key: "calcutta_auction", label: "Calcutta Auction" }],
    description: "Team-auction tournament ownership pool with round payouts.",
  }),

  // NBA
  def({
    key: "nba_pickem_pool",
    name: "NBA Pick'em Pool",
    sport: "nba",
    template: "pickem",
    league_or_tournament: "NBA",
    schedule_type: ["daily", "weekly", "season_long"],
    scoring_mode: ["straight_winner"],
    pick_mode: ["selected_games_or_all_games"],
    elimination_mode: ["none"],
    leaderboard_mode: ["daily", "weekly", "season"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    description: "NBA winner pick'em across daily/weekly/season horizons.",
  }),
  def({
    key: "nba_ats_pickem_pool",
    name: "NBA ATS Pick'em",
    sport: "nba",
    template: "ats_pickem",
    league_or_tournament: "NBA",
    schedule_type: ["daily", "weekly", "season_long"],
    scoring_mode: ["ats_win_loss_push"],
    pick_mode: ["spread_pick"],
    elimination_mode: ["none"],
    leaderboard_mode: ["daily", "weekly", "season"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    description: "NBA spread pick'em with ATS scoring.",
  }),
  def({
    key: "nba_streak_pool",
    name: "NBA Streak Pool",
    sport: "nba",
    template: "streak",
    league_or_tournament: "NBA",
    schedule_type: ["daily", "season_long"],
    scoring_mode: ["max_streak"],
    pick_mode: ["single_or_multi_nightly"],
    elimination_mode: ["reset_on_loss"],
    leaderboard_mode: ["streak_rank"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    description: "Streak pool tuned for high-frequency NBA schedules.",
  }),
  def({
    key: "nba_player_stat_pool",
    name: "NBA Player Stat Pool",
    sport: "nba",
    template: "stat_performance",
    league_or_tournament: "NBA",
    schedule_type: ["daily", "weekly", "season_long"],
    scoring_mode: ["stat_category_points"],
    pick_mode: ["player_stat_predictions"],
    elimination_mode: ["none"],
    leaderboard_mode: ["daily", "weekly", "season"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    aliases: ["stat"],
    description: "Player-stat outcome pool for NBA events.",
  }),
  def({
    key: "nba_survivor_pool",
    name: "NBA Survivor",
    sport: "nba",
    template: "survivor",
    league_or_tournament: "NBA",
    schedule_type: ["weekly", "season_long"],
    scoring_mode: ["survival"],
    pick_mode: ["one_team_per_week_no_reuse_default"],
    elimination_mode: ["lives_buy_back"],
    leaderboard_mode: ["survival_remaining"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    description: "NBA survivor with default no-reuse and optional buy-back.",
  }),
  def({
    key: "nba_last_man_standing_nights_pool",
    name: "NBA Last Man Standing Nights",
    sport: "nba",
    template: "last_man_standing",
    league_or_tournament: "NBA",
    schedule_type: ["daily", "season_long"],
    scoring_mode: ["night_survival"],
    pick_mode: ["one_or_two_teams_per_night"],
    elimination_mode: ["consecutive_night_elimination", "buy_back_night_optional"],
    leaderboard_mode: ["last_alive", "survival_rank"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    commissioner_options: ["team_reuse_toggle", "late_entry", "hidden_picks"],
    rule_variants: [{ key: "lms_nights", label: "Last Man Standing Nights" }],
    description: "Nightly elimination variant with optional two-pick cards.",
  }),
  def({
    key: "nba_playoff_bracket_pool",
    name: "NBA Playoff Bracket",
    sport: "nba",
    template: "bracket",
    league_or_tournament: "NBA Playoffs",
    schedule_type: ["tournament"],
    scoring_mode: ["round_weighted"],
    pick_mode: ["playoff_bracket"],
    elimination_mode: ["none"],
    leaderboard_mode: ["playoff"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    description: "NBA playoff bracket predictions.",
  }),
  def({
    key: "nba_finals_squares_pool",
    name: "NBA Finals Squares",
    sport: "nba",
    template: "squares",
    league_or_tournament: "NBA Finals",
    schedule_type: ["tournament"],
    scoring_mode: ["board_square_payouts"],
    pick_mode: ["square_selection"],
    elimination_mode: ["none"],
    leaderboard_mode: ["series_board"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    description: "Series squares for NBA Finals.",
  }),

  // MLB
  def({
    key: "mlb_pickem_pool",
    name: "MLB Pick'em",
    sport: "mlb",
    template: "pickem",
    league_or_tournament: "MLB",
    schedule_type: ["daily", "weekly", "season_long"],
    scoring_mode: ["straight_winner"],
    pick_mode: ["daily_slate"],
    elimination_mode: ["none"],
    leaderboard_mode: ["daily", "weekly", "season"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    description: "Daily and season MLB winner picks.",
  }),
  def({
    key: "mlb_survivor_pool",
    name: "MLB Survivor",
    sport: "mlb",
    template: "survivor",
    league_or_tournament: "MLB",
    schedule_type: ["daily", "season_long"],
    scoring_mode: ["survival"],
    pick_mode: ["single_pick_no_reuse"],
    elimination_mode: ["one_life", "lives_buy_back"],
    leaderboard_mode: ["survival_remaining"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    description: "MLB survivor format with optional re-entry controls.",
  }),
  def({
    key: "mlb_series_winner_pool",
    name: "MLB Series Winner Pool",
    sport: "mlb",
    template: "pickem",
    league_or_tournament: "MLB",
    schedule_type: ["weekly", "season_long"],
    scoring_mode: ["series_winner_points"],
    pick_mode: ["series_pick"],
    elimination_mode: ["none"],
    leaderboard_mode: ["weekly", "season"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    description: "Pick winners for MLB series sets.",
  }),
  def({
    key: "mlb_run_line_pool",
    name: "MLB Run Line Pool",
    sport: "mlb",
    template: "ats_pickem",
    league_or_tournament: "MLB",
    schedule_type: ["daily", "weekly", "season_long"],
    scoring_mode: ["run_line_cover"],
    pick_mode: ["run_line_pick"],
    elimination_mode: ["none"],
    leaderboard_mode: ["daily", "weekly", "season"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    description: "Run-line equivalent ATS pool for baseball.",
  }),
  def({
    key: "mlb_streak_pool",
    name: "MLB Streak Pool",
    sport: "mlb",
    template: "streak",
    league_or_tournament: "MLB",
    schedule_type: ["daily", "season_long"],
    scoring_mode: ["streak"],
    pick_mode: ["daily_pick"],
    elimination_mode: ["reset_on_loss"],
    leaderboard_mode: ["max_streak"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    description: "Beat-the-streak style MLB run.",
  }),
  def({
    key: "mlb_home_run_pool",
    name: "MLB Home Run Pool",
    sport: "mlb",
    template: "prop",
    league_or_tournament: "MLB",
    schedule_type: ["daily", "weekly", "season_long"],
    scoring_mode: ["hr_pick_points"],
    pick_mode: ["home_run_predictions"],
    elimination_mode: ["none"],
    leaderboard_mode: ["daily", "weekly", "season"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    description: "Home run prediction contest.",
  }),
  def({
    key: "mlb_playoff_bracket_pool",
    name: "MLB Playoff Bracket",
    sport: "mlb",
    template: "bracket",
    league_or_tournament: "MLB Playoffs",
    schedule_type: ["tournament"],
    scoring_mode: ["round_weighted"],
    pick_mode: ["playoff_bracket"],
    elimination_mode: ["none"],
    leaderboard_mode: ["playoff"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    description: "MLB postseason bracket format.",
  }),
  def({
    key: "mlb_beat_the_streak_pool",
    name: "MLB Beat the Streak Pool",
    sport: "mlb",
    template: "streak",
    league_or_tournament: "MLB",
    schedule_type: ["daily", "season_long"],
    scoring_mode: ["progressive_streak"],
    pick_mode: ["single_player_hit_pick"],
    elimination_mode: ["reset_on_miss"],
    leaderboard_mode: ["max_streak"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    description: "Classic hit-streak contest support.",
  }),
  def({
    key: "mlb_daily_dogfight_pool",
    name: "MLB Daily Dogfight Pool",
    sport: "mlb",
    template: "upset_underdog",
    league_or_tournament: "MLB",
    schedule_type: ["daily", "weekly", "season_long"],
    scoring_mode: ["odds_based", "fixed_points_optional"],
    pick_mode: ["one_or_many_daily"],
    elimination_mode: ["none"],
    leaderboard_mode: ["daily", "weekly", "season"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    commissioner_options: [
      "underdogs_only_mode",
      "favorites_only_mode",
      "mixed_mode",
      "drop_worst_days",
      "best_x_days",
      "weekly_winners",
      "hidden_picks",
    ],
    rule_variants: [{ key: "daily_dogfight", label: "Daily Dogfight" }],
    description: "Odds-based daily dogfight with daily/season standings.",
  }),

  // NHL
  def({
    key: "nhl_pickem_pool",
    name: "NHL Pick'em",
    sport: "nhl",
    template: "pickem",
    league_or_tournament: "NHL",
    schedule_type: ["daily", "weekly", "season_long"],
    scoring_mode: ["straight_winner"],
    pick_mode: ["selected_games"],
    elimination_mode: ["none"],
    leaderboard_mode: ["daily", "weekly", "season"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    description: "NHL winner pick'em.",
  }),
  def({
    key: "nhl_puck_line_pool",
    name: "NHL Puck Line Pool",
    sport: "nhl",
    template: "ats_pickem",
    league_or_tournament: "NHL",
    schedule_type: ["daily", "weekly", "season_long"],
    scoring_mode: ["puck_line_cover"],
    pick_mode: ["puck_line_pick"],
    elimination_mode: ["none"],
    leaderboard_mode: ["daily", "weekly", "season"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    description: "NHL puck-line equivalent ATS pool.",
  }),
  def({
    key: "nhl_survivor_pool",
    name: "NHL Survivor",
    sport: "nhl",
    template: "survivor",
    league_or_tournament: "NHL",
    schedule_type: ["weekly", "season_long"],
    scoring_mode: ["survival"],
    pick_mode: ["single_pick"],
    elimination_mode: ["lives_buy_back"],
    leaderboard_mode: ["survival"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    description: "NHL survivor mode.",
  }),
  def({
    key: "nhl_streak_pool",
    name: "NHL Streak Pool",
    sport: "nhl",
    template: "streak",
    league_or_tournament: "NHL",
    schedule_type: ["daily", "season_long"],
    scoring_mode: ["streak"],
    pick_mode: ["nightly_pick"],
    elimination_mode: ["reset_on_loss"],
    leaderboard_mode: ["max_streak"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    description: "NHL streak tracking pool.",
  }),
  def({
    key: "nhl_goal_scorer_pool",
    name: "NHL Goal Scorer Pool",
    sport: "nhl",
    template: "prop",
    league_or_tournament: "NHL",
    schedule_type: ["daily", "weekly", "season_long"],
    scoring_mode: ["goal_scorer_points"],
    pick_mode: ["goal_scorer_pick"],
    elimination_mode: ["none"],
    leaderboard_mode: ["daily", "weekly", "season"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    description: "Player goal scorer prediction pool.",
  }),
  def({
    key: "nhl_goalie_win_pool",
    name: "NHL Goalie Win Pool",
    sport: "nhl",
    template: "stat_performance",
    league_or_tournament: "NHL",
    schedule_type: ["daily", "weekly", "season_long"],
    scoring_mode: ["goalie_win_points"],
    pick_mode: ["goalie_selection"],
    elimination_mode: ["none"],
    leaderboard_mode: ["daily", "weekly", "season"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    description: "Goalie win tracking pool.",
  }),
  def({
    key: "nhl_playoff_bracket_pool",
    name: "NHL Playoff Bracket",
    sport: "nhl",
    template: "bracket",
    league_or_tournament: "NHL Playoffs",
    schedule_type: ["tournament"],
    scoring_mode: ["round_weighted"],
    pick_mode: ["playoff_bracket"],
    elimination_mode: ["none"],
    leaderboard_mode: ["playoff"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    description: "NHL playoff bracket pool.",
  }),
  def({
    key: "nhl_shutout_pool",
    name: "NHL Shutout Pool",
    sport: "nhl",
    template: "prop",
    league_or_tournament: "NHL",
    schedule_type: ["daily", "weekly", "season_long"],
    scoring_mode: ["shutout_predictions"],
    pick_mode: ["shutout_pick"],
    elimination_mode: ["none"],
    leaderboard_mode: ["daily", "weekly", "season"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    description: "Shutout prediction format.",
  }),
  def({
    key: "nhl_overtime_chaos_pool",
    name: "NHL Overtime Chaos Pool",
    sport: "nhl",
    template: "upset_underdog",
    league_or_tournament: "NHL",
    schedule_type: ["daily", "weekly", "season_long"],
    scoring_mode: ["ot_game_hit", "shootout_bonus"],
    pick_mode: ["specific_games_or_total_ot_count"],
    elimination_mode: ["none"],
    leaderboard_mode: ["daily", "weekly", "season"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    commissioner_options: ["ot_pick_count_1_to_5_or_unlimited", "shootout_bonus", "hidden_picks"],
    rule_variants: [{ key: "overtime_chaos", label: "Overtime Chaos" }],
    description: "Predict OT games or total OT count with shootout bonus.",
  }),

  // Golf
  def({
    key: "golf_one_and_done_pool",
    name: "Golf One & Done",
    sport: "golf",
    template: "stat_performance",
    league_or_tournament: "PGA / Golf",
    schedule_type: ["season_long", "tournament"],
    scoring_mode: ["one_and_done_earnings_or_points"],
    pick_mode: ["single_golfer_no_reuse"],
    elimination_mode: ["none"],
    leaderboard_mode: ["season", "event"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    rule_variants: [{ key: "one_and_done", label: "One & Done" }],
    description: "Pick one golfer per event with no reuse.",
  }),
  def({
    key: "golf_pick_3_pick_5_pool",
    name: "Golf Pick 3 / Pick 5",
    sport: "golf",
    template: "pickem",
    league_or_tournament: "PGA / Golf",
    schedule_type: ["tournament", "season_long"],
    scoring_mode: ["aggregate_finish_points"],
    pick_mode: ["pick_3_or_pick_5"],
    elimination_mode: ["none"],
    leaderboard_mode: ["event", "season"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    rule_variants: [
      { key: "pick3", label: "Pick 3" },
      { key: "pick5", label: "Pick 5" },
    ],
    description: "Pick 3 or 5 golfers and score by aggregate finish.",
  }),
  def({
    key: "golf_survivor_pool",
    name: "Golf Survivor",
    sport: "golf",
    template: "survivor",
    league_or_tournament: "PGA / Golf",
    schedule_type: ["tournament", "season_long"],
    scoring_mode: ["survival_cut_line"],
    pick_mode: ["golfer_survival_pick"],
    elimination_mode: ["missed_cut_elimination"],
    leaderboard_mode: ["survival"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    description: "Survivor mode for golf cuts/events.",
  }),
  def({
    key: "golf_tournament_winner_pool",
    name: "Golf Tournament Winner Pool",
    sport: "golf",
    template: "pickem",
    league_or_tournament: "PGA / Golf",
    schedule_type: ["tournament"],
    scoring_mode: ["winner_pick_points"],
    pick_mode: ["winner_pick"],
    elimination_mode: ["none"],
    leaderboard_mode: ["event", "season"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    description: "Tournament winner prediction format.",
  }),
  def({
    key: "golf_birdie_pool",
    name: "Golf Birdie Pool",
    sport: "golf",
    template: "stat_performance",
    league_or_tournament: "PGA / Golf",
    schedule_type: ["tournament", "season_long"],
    scoring_mode: ["birdie_count_points"],
    pick_mode: ["birdie_prediction"],
    elimination_mode: ["none"],
    leaderboard_mode: ["event", "season"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    description: "Birdie-based scoring pool.",
  }),

  // UFC / MMA
  def({
    key: "mma_fight_card_pickem_pool",
    name: "Fight Card Pick'em",
    sport: "mma",
    template: "pickem",
    league_or_tournament: "UFC / MMA",
    schedule_type: ["tournament", "weekly"],
    scoring_mode: ["fight_winner_points"],
    pick_mode: ["fight_card_selection"],
    elimination_mode: ["none"],
    leaderboard_mode: ["card", "season"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    description: "Pick winners across full MMA card.",
  }),
  def({
    key: "mma_method_pool",
    name: "MMA Method Pool",
    sport: "mma",
    template: "prop",
    league_or_tournament: "UFC / MMA",
    schedule_type: ["tournament", "weekly"],
    scoring_mode: ["method_of_victory_points"],
    pick_mode: ["method_prediction"],
    elimination_mode: ["none"],
    leaderboard_mode: ["card", "season"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    description: "Predict finish method for selected fights.",
  }),
  def({
    key: "mma_round_prediction_pool",
    name: "MMA Round Prediction Pool",
    sport: "mma",
    template: "prop",
    league_or_tournament: "UFC / MMA",
    schedule_type: ["tournament", "weekly"],
    scoring_mode: ["round_hit_points"],
    pick_mode: ["round_prediction"],
    elimination_mode: ["none"],
    leaderboard_mode: ["card", "season"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    description: "Round prediction pool for MMA fights.",
  }),
  def({
    key: "mma_survivor_pool",
    name: "MMA Survivor Pool",
    sport: "mma",
    template: "survivor",
    league_or_tournament: "UFC / MMA",
    schedule_type: ["weekly", "season_long"],
    scoring_mode: ["survival"],
    pick_mode: ["fighter_pick"],
    elimination_mode: ["one_life", "lives_buy_back"],
    leaderboard_mode: ["survival"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    description: "Survivor pool for fight cards.",
  }),
  def({
    key: "mma_finish_points_pool",
    name: "MMA Finish Points Pool",
    sport: "mma",
    template: "stat_performance",
    league_or_tournament: "UFC / MMA",
    schedule_type: ["weekly", "season_long"],
    scoring_mode: ["finish_points"],
    pick_mode: ["finish_prediction"],
    elimination_mode: ["none"],
    leaderboard_mode: ["card", "season"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    description: "Scored by KO/TKO/submission/decision outcomes.",
  }),

  // NASCAR
  def({
    key: "nascar_race_winner_pool",
    name: "NASCAR Race Winner Pool",
    sport: "nascar",
    template: "pickem",
    league_or_tournament: "NASCAR",
    schedule_type: ["weekly", "season_long"],
    scoring_mode: ["winner_pick_points"],
    pick_mode: ["race_winner_pick"],
    elimination_mode: ["none"],
    leaderboard_mode: ["race", "season"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    description: "Pick race winners across NASCAR season.",
  }),
  def({
    key: "nascar_top5_pool",
    name: "NASCAR Top 5 Pool",
    sport: "nascar",
    template: "stat_performance",
    league_or_tournament: "NASCAR",
    schedule_type: ["weekly", "season_long"],
    scoring_mode: ["top5_hit_points"],
    pick_mode: ["top5_prediction"],
    elimination_mode: ["none"],
    leaderboard_mode: ["race", "season"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    description: "Predict top-5 drivers and score by hits/placement.",
  }),
  def({
    key: "nascar_survivor_pool",
    name: "NASCAR Survivor",
    sport: "nascar",
    template: "survivor",
    league_or_tournament: "NASCAR",
    schedule_type: ["weekly", "season_long"],
    scoring_mode: ["survival"],
    pick_mode: ["driver_survival_pick"],
    elimination_mode: ["one_life", "lives_buy_back"],
    leaderboard_mode: ["survival"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    description: "Driver survivor across NASCAR schedule.",
  }),
  def({
    key: "nascar_manufacturer_pool",
    name: "NASCAR Manufacturer Pool",
    sport: "nascar",
    template: "pickem",
    league_or_tournament: "NASCAR",
    schedule_type: ["weekly", "season_long"],
    scoring_mode: ["manufacturer_points"],
    pick_mode: ["manufacturer_pick"],
    elimination_mode: ["none"],
    leaderboard_mode: ["race", "season"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    description: "Pick manufacturer outcomes.",
  }),
  def({
    key: "nascar_pole_position_pool",
    name: "NASCAR Pole Position Pool",
    sport: "nascar",
    template: "prop",
    league_or_tournament: "NASCAR",
    schedule_type: ["weekly", "season_long"],
    scoring_mode: ["pole_hit_points"],
    pick_mode: ["pole_prediction"],
    elimination_mode: ["none"],
    leaderboard_mode: ["race", "season"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    description: "Pole position prediction pool.",
  }),
  def({
    key: "nascar_crash_pool",
    name: "NASCAR Crash Pool",
    sport: "nascar",
    template: "prop",
    league_or_tournament: "NASCAR",
    schedule_type: ["weekly", "season_long"],
    scoring_mode: ["incident_prediction_points"],
    pick_mode: ["crash_prediction"],
    elimination_mode: ["none"],
    leaderboard_mode: ["race", "season"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    description: "Crash/incident prediction format.",
  }),

  // Soccer
  def({
    key: "soccer_world_cup_bracket_pool",
    name: "World Cup Bracket",
    sport: "soccer",
    template: "bracket",
    league_or_tournament: "World Cup",
    schedule_type: ["tournament"],
    scoring_mode: ["round_weighted", "draw_handling_options"],
    pick_mode: ["full_bracket"],
    elimination_mode: ["none"],
    leaderboard_mode: ["tournament"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    description: "World Cup bracket predictions with draw/advance handling.",
  }),
  def({
    key: "soccer_group_stage_pickem_pool",
    name: "Soccer Group Stage Pick'em",
    sport: "soccer",
    template: "pickem",
    league_or_tournament: "Soccer Tournament Group Stage",
    schedule_type: ["tournament"],
    scoring_mode: ["win_draw_loss_or_advance"],
    pick_mode: ["group_stage_match_pickem"],
    elimination_mode: ["none"],
    leaderboard_mode: ["group_stage"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    commissioner_options: ["draw_handling", "win_only_vs_advance_draw_options"],
    description: "Group-stage pick'em with draw handling.",
  }),
  def({
    key: "soccer_exact_score_pool",
    name: "Soccer Exact Score Pool",
    sport: "soccer",
    template: "prop",
    league_or_tournament: "Soccer",
    schedule_type: ["daily", "weekly", "tournament"],
    scoring_mode: ["exact_score_points", "near_miss_points_optional"],
    pick_mode: ["scoreline_prediction"],
    elimination_mode: ["none"],
    leaderboard_mode: ["daily", "weekly", "tournament", "season"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    description: "Exact scoreline prediction pool.",
  }),
  def({
    key: "soccer_golden_boot_pool",
    name: "Soccer Golden Boot Pool",
    sport: "soccer",
    template: "stat_performance",
    league_or_tournament: "Soccer Tournament",
    schedule_type: ["tournament", "season_long"],
    scoring_mode: ["goal_scorer_totals"],
    pick_mode: ["top_scorer_pick"],
    elimination_mode: ["none"],
    leaderboard_mode: ["tournament", "season"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    description: "Top scorer / golden boot pool.",
  }),
  def({
    key: "soccer_tournament_survivor_pool",
    name: "Soccer Tournament Survivor",
    sport: "soccer",
    template: "survivor",
    league_or_tournament: "World Cup / Tournament",
    schedule_type: ["tournament"],
    scoring_mode: ["survival"],
    pick_mode: ["team_survival_pick"],
    elimination_mode: ["one_life", "lives_buy_back"],
    leaderboard_mode: ["survival"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    description: "Tournament survivor for soccer events.",
  }),
  def({
    key: "soccer_goal_minute_pool",
    name: "Soccer Goal Minute Pool",
    sport: "soccer",
    template: "prop",
    league_or_tournament: "Soccer",
    schedule_type: ["daily", "weekly", "tournament"],
    scoring_mode: ["goal_minute_accuracy_points"],
    pick_mode: ["goal_minute_prediction"],
    elimination_mode: ["none"],
    leaderboard_mode: ["daily", "weekly", "season"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    description: "Predict timing of first/any goal events.",
  }),
  def({
    key: "soccer_last_man_standing_pool",
    name: "Soccer Last Man Standing",
    sport: "soccer",
    template: "last_man_standing",
    league_or_tournament: "Soccer",
    schedule_type: ["weekly", "season_long", "tournament"],
    scoring_mode: ["survival"],
    pick_mode: ["team_pick"],
    elimination_mode: ["eliminate_on_miss"],
    leaderboard_mode: ["survival"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    rule_variants: [{ key: "soccer_lms", label: "Soccer LMS" }],
    description: "Soccer last-man-standing format.",
  }),
  def({
    key: "soccer_big_upset_pool",
    name: "Soccer Big Upset Pool",
    sport: "soccer",
    template: "upset_underdog",
    league_or_tournament: "Soccer",
    schedule_type: ["weekly", "season_long", "tournament"],
    scoring_mode: ["underdog_value"],
    pick_mode: ["upset_pick"],
    elimination_mode: ["none"],
    leaderboard_mode: ["weekly", "season"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    description: "Soccer upset challenge with underdog weighting.",
  }),
  def({
    key: "soccer_mixed_league_survivor_pool",
    name: "Mixed League Soccer Survivor",
    sport: "soccer",
    template: "survivor",
    league_or_tournament: "Mixed League Soccer",
    schedule_type: ["weekly", "season_long"],
    scoring_mode: ["survival"],
    pick_mode: ["mixed_league_team_pick"],
    elimination_mode: ["one_life", "lives_buy_back"],
    leaderboard_mode: ["survival", "season"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    commissioner_options: [
      "mixed_league_sources_mls",
      "mixed_league_sources_premier_league",
      "mixed_league_sources_la_liga",
      "mixed_league_sources_champions_league",
      "mixed_league_sources_world_cup",
      "mixed_league_sources_other_future",
      "draw_handling",
      "win_only_vs_advance_draw_options",
    ],
    rule_variants: [{ key: "mixed_league_survivor", label: "Mixed League Survivor" }],
    description: "Cross-league soccer survivor with source controls.",
  }),

  // Multi-sport
  def({
    key: "all_sport_survivor_pool",
    name: "All-Sport Survivor",
    sport: "multi_sport",
    template: "survivor",
    league_or_tournament: "All Sports",
    schedule_type: ["weekly", "season_long"],
    scoring_mode: ["survival"],
    pick_mode: ["one_team_from_any_enabled_sport"],
    elimination_mode: ["no_reuse_default", "lives_strikes_buy_back"],
    leaderboard_mode: ["survival", "season"],
    entry_mode: ["single_entry", "multi_entry"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    commissioner_options: ["eligible_sports_and_leagues_selection"],
    rule_variants: [{ key: "all_american_survivor", label: "All-American Survivor" }],
    description: "All-sport survivor with commissioner-controlled sport set.",
  }),

  // Bundle pool
  def({
    key: "bundle_pool_master",
    name: "Bundle Pool",
    sport: "multi_sport",
    template: "bundle_pool",
    league_or_tournament: "Any",
    schedule_type: ["weekly", "season_long", "tournament"],
    scoring_mode: ["per_child_pool_scoring", "optional_overall_bundle_scoring"],
    pick_mode: ["bundle_child_pool_submission"],
    elimination_mode: ["independent_per_child_pool"],
    leaderboard_mode: ["child_pool", "overall_bundle_optional"],
    entry_mode: ["single_bundle_entry", "shared_or_independent_child_participants"],
    payout_bucket_support: true,
    multi_pool_bundle_support: true,
    commissioner_options: [...BUNDLE_OPTIONS],
    rule_variants: [{ key: "bundle_master", label: "Bundle Master" }],
    aliases: ["bundle", "bundle_pool"],
    description: "Master bundle pool with linked child pools and payout buckets.",
  }),
];

const LEGACY_TEMPLATE_ALIASES: Record<string, PoolTemplateKey> = {
  pickem: "pickem",
  "pick-em": "pickem",
  pick_em: "pickem",
  ats: "ats_pickem",
  confidence: "confidence",
  survivor: "survivor",
  bracket: "bracket",
  squares: "squares",
  props: "prop",
  streak: "streak",
  upset: "upset_underdog",
  underdog: "upset_underdog",
  stat: "stat_performance",
  special: "bundle_pool",
  last_man_standing: "last_man_standing",
  bundle: "bundle_pool",
  bundle_pool: "bundle_pool",
};

export function normalizePoolTypeKey(input: string): string {
  return slug(input);
}

export function getPoolTypeByKey(input: string): PoolTypeDefinition | null {
  const normalized = normalizePoolTypeKey(input);
  for (const item of POOL_TYPE_CATALOG) {
    if (normalizePoolTypeKey(item.key) === normalized) return item;
    if ((item.aliases || []).some((alias) => normalizePoolTypeKey(alias) === normalized)) return item;
  }
  return null;
}

export function getPoolTypesBySport(sport: PoolSportKey): PoolTypeDefinition[] {
  return POOL_TYPE_CATALOG.filter((item) => item.sport === sport || item.sport === "multi_sport");
}

export function isSupportedPoolTypeKey(input: string): boolean {
  const normalized = normalizePoolTypeKey(input);
  if (Boolean(getPoolTypeByKey(normalized))) return true;
  return Boolean(LEGACY_TEMPLATE_ALIASES[normalized]);
}

export function getTemplateForPoolType(input: string): PoolTemplateKey | null {
  const definition = getPoolTypeByKey(input);
  if (definition) return definition.template;
  const normalized = normalizePoolTypeKey(input);
  return LEGACY_TEMPLATE_ALIASES[normalized] || null;
}

export function getCanonicalEvaluatorPoolType(input: string): string | null {
  const template = getTemplateForPoolType(input);
  if (!template) return null;
  if (template === "pickem") return "pickem";
  if (template === "ats_pickem") return "ats";
  if (template === "confidence") return "confidence";
  if (template === "ats_confidence") return "confidence";
  if (template === "survivor") return "survivor";
  if (template === "bracket") return "bracket";
  if (template === "squares") return "squares";
  if (template === "prop") return "props";
  if (template === "streak") return "streak";
  if (template === "upset_underdog") return "upset";
  if (template === "stat_performance") return "stat";
  if (template === "last_man_standing") return "survivor";
  if (template === "bundle_pool") return "special";
  return null;
}

export function buildLegacyAllowedSettings(definition: PoolTypeDefinition): string[] {
  const out = new Set<string>();
  const options = definition.commissioner_options.join(" ");
  if (options.includes("entry")) out.add("entry_fee");
  if (options.includes("entries")) out.add("max_entries");
  if (options.includes("late")) out.add("late_entry");
  if (options.includes("lock")) out.add("auto_lock");
  if (options.includes("tie")) out.add("tiebreaker");
  if (options.includes("payout")) out.add("payout_structure");
  if (options.includes("visibility") || options.includes("hidden")) out.add("visibility");
  if (options.includes("notify")) out.add("notifications");
  if (options.includes("reentry") || options.includes("buy_back")) out.add("reentry");
  if (options.includes("multiple_entries") || options.includes("multi_entry")) out.add("multi_entry");
  return Array.from(out);
}

export function getPoolTypeTraceabilityChecklist(): Record<string, string[]> {
  return {
    supported_sports: SUPPORTED_SPORTS,
    core_templates: CORE_POOL_TEMPLATES,
    pool_type_keys: POOL_TYPE_CATALOG.map((item) => item.key),
  };
}

export function validatePoolTypeRules(input: {
  sportKey: string;
  formatKey: string;
  rules?: Record<string, unknown> | null;
}): string[] {
  const errors: string[] = [];
  const definition = getPoolTypeByKey(input.formatKey);
  if (!definition && !isSupportedPoolTypeKey(input.formatKey)) {
    errors.push(`Unsupported format key: ${input.formatKey}`);
    return errors;
  }
  if (definition && definition.sport !== "multi_sport" && definition.sport !== input.sportKey) {
    errors.push(`Format ${definition.key} does not support sport ${input.sportKey}`);
  }
  const rules = (input.rules || {}) as Record<string, unknown>;
  if (definition?.template === "bundle_pool") {
    const childPools = Array.isArray(rules.bundleChildPools) ? rules.bundleChildPools : [];
    if (childPools.length === 0) {
      errors.push("Bundle pools require at least one child pool in rules.bundleChildPools");
    }
  }
  if (definition?.template === "confidence" || definition?.template === "ats_confidence") {
    const confidenceMode = typeof rules.confidenceMode === "string" ? rules.confidenceMode : "";
    if (!confidenceMode && !rules.pointsPerWin) {
      errors.push("Confidence pools require confidenceMode or pointsPerWin configuration");
    }
  }
  const maxEntries = Number(rules.maxEntries ?? 0);
  if (maxEntries < 0 || !Number.isFinite(maxEntries)) {
    errors.push("rules.maxEntries must be a non-negative number when provided");
  }
  if (rules.payoutStructure !== undefined && !Array.isArray(rules.payoutStructure)) {
    errors.push("rules.payoutStructure must be an array when provided");
  }
  return errors;
}
